name: Change Dependabot Branch Base 🔄
on: pull_request_target

jobs:
  dependabot:
    uses: austenstone/.github/.github/workflows/dependabot-change-branch.yml@main
    with:
      length: 10
      prefix: austen-